[toolchain]
solana_version = "1.16.23"

[features]
seeds = true
skip-lint = false

[programs.localnet]
marginfi = "neetcne3Ctrrud7vLdt2ypMm21gZHGN2mCmqWaMVcBQ"
liquidity_incentive_program = "sexyDKo4Khm38YdJeiRdNNd5aMQqNtfDkxv7MnYNFeU"

[programs.devnet]
marginfi = "neetcne3Ctrrud7vLdt2ypMm21gZHGN2mCmqWaMVcBQ"
liquidity_incentive_program = "sexyDKo4Khm38YdJeiRdNNd5aMQqNtfDkxv7MnYNFeU"

[programs.mainnet]
marginfi = "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA"
liquidity_incentive_program = "LipsxuAkFkwa4RKNzn51wAsW7Dedzt1RNHMkTkDEZUW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.rpcpool.com/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "8FRFC6MoGGkMFQwngccyu69VnYbzykGeez7ignHVAFSN"
filename = "tests/fixtures/localnet_usdc.json"
